### ISSUE TITLE
plugin install how to

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern-plugins-website#20]
Consider adding a short note about different type of plugins and the various ways to install a plugin - and link to the relevant docs page (https://Docs.Textpattern.Com/administration/plugins-panel). The pop help text on the plugins panel could serve as a template.

@Bloke would now about the latest details included in a future 4.8.2

**Comment by Bloke** [comment]
Thanks for the nudge.

That page, and all other "this is the abc panel" docs, are going to be trawled for content to make better docs specifically targeted at user tasks rather than just about that panel. Then they'll be deleted.

To that end, I've created a document for the new home regarding plugins, and we can fill it out as time permits:

[Installing, upgrading and using plugins](https://docs.textpattern.com/build/plugins-installing-upgrading-and-using).

**Comment by Bloke** [comment]
Not entirely sure whether the 'Construction and Presentation' area is the best place for it, btw. Suggestions on a better home or site architecture from our revised, upcoming [index page](https://docs.textpattern.com/index2) are welcome.

**Comment by philwareham** [comment]
Soon I will be adding a 'how to install' section to plugin pages, which shows one or both of the methods (depending on whether TXT and/or PHP files are available). Bear with me - should be next week sometime.
